WebApp-B2C-DotNet/Controllers/PingisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp_OpenIDConnect_DotNet_B2C.Controllers
{
    public class PingisController : BaseController
    {
        [Authorize]
        // GET: Pingis
        public ActionResult Index()
        {
            ViewBag.CurrentUserId = currentUserId;
            return View();
        }

        public ActionResult HighScore()
        {
            return View();
        }
    }
}

WebApp-B2C-DotNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="gameapp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pingis App</title>
    @Styles.Render("~/Content/appcss")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ÅF Pingis App", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Home</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Pingis")"><i class="fa fa-gamepad"></i> Pingis</a>
                    </li>
                    <li><a href="https://github.com/syron/gametrackingapp/issues" target="_blank"><i class="fa fa-lightbulb-o"></i> Feature Requests</a></li>
                    <li><a href="https://github.com/syron/gametrackingapp/" target="_blank"><i class="fa fa-github"></i> Source Code</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="http://robertmayer.se/">Robert Mayer</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/profile-dropdown.js"></script>
</body>
</html>

WebApp-B2C-DotNet/Views/Shared/_LayoutWidget.cshtml
<!DOCTYPE html>
<html ng-app="gameapp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pingis App</title>
    @Styles.Render("~/Content/appcss")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px; padding: 0;">
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/profile-dropdown.js"></script>
</body>
</html>